server.port=${PORT:8082}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/stock_db}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:root}
spring.jpa.show-sql: true

#Initialize the datasource with available DDL and DML scripts
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#comma seperated hosts
app.cors.allowedOrigins=${ALLOWED_ORIGINS:http://localhost:3000}
