server.port=${PORT:9000}

##spring datasource
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/stock_db}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:root}
 
##hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update

##Hibernate logging
logging.level.org.hibernate.SQL=DEBUG

#Initialize the datasource with available DDL and DML scripts
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.jwtSecret=${JWT_SECRET:9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f}
app.jwtExpirationInMs = 604800000

#comma seperated hosts
app.cors.allowedOrigins=${ALLOWED_ORIGINS:http://localhost:3000}
